"""se agrego el campo status entabla roles

Revision ID: 64406230429b
Revises: a5cd24aa86bf
Create Date: 2022-09-03 10:13:29.936808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64406230429b'
down_revision = 'a5cd24aa86bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'status')
    # ### end Alembic commands ###
