"""se agregro campo de status al modelo de usurio

Revision ID: bf82b8a278d4
Revises: 64406230429b
Create Date: 2022-09-05 22:08:13.581455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf82b8a278d4'
down_revision = '64406230429b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('status', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'status')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
